l2p-dbcq-offline:
    env: Acrobot-v1
    run: contrib/DBCQ
    config:
        num_gpus: 1
        input: "/home/guy/share/Data/MLA/ray/acrobot-rnd"
        input_evaluation: ['is','wis']
        shuffle_buffer_size: 100
        explore: False
        lr: 0.0001
        hiddens: [64,128]
        target_network_update_freq: 512
        buffer_size: 100000
        train_batch_size: 128
    stop:
        timesteps_total: 10000000



