cartpole-dqn:
    env: CartPole-v0
    run: DQN
    config:
        num_gpus: 1
    stop:
        timesteps_total: 1000000
    flow_config:
        callbacks:
            on_episode_start: true
            on_episode_end: false
            on_train_result: true




